name: Build and Deploy Documentation

on:
    # Image is build when someone pushes to main branch
    push:
        branches:
            - main

    # Image is build when a PR to develop is closed
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    build:
        name: Build App
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '18.x'
          - run: npm ci
          - run: cp config/user-config.sample.js config/user-config.js
          - run: npm run build
          - name: Login to PISTIS Registry
            uses: docker/login-action@v3
            with:
              registry: registry.pistis-market.eu
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/amd64
              push: true
              tags: pistis/pistis-catalog-ui:latest
